### ISSUE TITLE
Fix Renewable Potential Chart

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#134]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Something is wrong with the scaling in the renewable potential map 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/7f0f2070-81cc-4f7b-a202-4fa6f9a1e212)

### Steps To Reproduce

1. Run the workflow 
2. Check the renewable potential map

**Comment by ktehranchi** [comment]
@trevorb1 This seems to be fixed... did you fix without tagging?

**Comment by trevorb1** [comment]
@ktehranchi yeah. Forgot to close with PR #133
