### ISSUE TITLE
Error in build_renewable_profiles

### ISSUE THREAD

**Issue by nomineb** [PyPSA/pypsa-usa#136]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

When run the workflow (snakemake -j4), I'm running into an error in rule build_renewable_profiles.

### Steps To Reproduce

1. snakemake -j4
2. default config file
3. error in build_renewable_profiles rule

### Expected Behavior

The workflow doesn't finish running, and stops at error in build_renewable_profiles rule.

### Error Message

```
Traceback (most recent call last):
  File "/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/.snakemake/scripts/tmp0gdwyiln.build_renewable_profiles.py", line 226, in <module>
    cutout = atlite.Cutout(snakemake.input.cutout).sel(time=sns)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/atlite/cutout.py", line 441, in sel
    data = self.data.sel(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/core/dataset.py", line 2653, in sel
    query_results = map_index_queries(
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/core/indexing.py", line 190, in map_index_queries
    results.append(index.sel(labels, **options))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/core/indexes.py", line 498, in sel
    raise KeyError(f"not all values found in index {coord_name!r}")
KeyError: "not all values found in index 'time'"
[Tue Dec  5 18:48:58 2023]
Error in rule build_renewable_profiles:
    jobid: 14
    input: resources/western/elec_base_network.nc, data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_USA_EPSG-4326.tif, data/natura.tiff, resources/western/country_shapes.geojson, resources/western/offshore_shapes.geojson, resources/western/regions_onshore.geojson, cutouts/western_era5_2019.nc
    output: resources/western/profile_solar.nc
    log: logs/western/build_renewable_profile_solar.log (check log file(s) for error details)

RuleException:
CalledProcessError in file /Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/Snakefile, line 431:
Command 'set -euo pipefail;  /Users/nomio/miniforge3/envs/pypsa-usa/bin/python3.11 /Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/.snakemake/scripts/tmp0gdwyiln.build_renewable_profiles.py' returned non-zero exit status 1.
  File "/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/Snakefile", line 431, in __rule_build_renewable_profiles
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by trevorb1** [comment]
Hi @nomineb! Are you able to check if you can open the dataset outside of the workflow with xarray in a notebook? This will help narrow down the problem if it is in the reading or writing of the dataset. 

```python 
import xarray as xr 
xr.open_dataset("/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/cutouts/western_era5_2019.nc")
```

**Comment by nomineb** [comment]
Hi @trevorb1! I'm getting this error when I try to open the dataset:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/file_manager.py:210, in CachingFileManager._acquire_with_cache_info(self, needs_lock)
    209 try:
--> 210     file = self._cache[self._key]
    211 except KeyError:

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/lru_cache.py:56, in LRUCache.__getitem__(self, key)
     55 with self._lock:
---> 56     value = self._cache[key]
     57     self._cache.move_to_end(key)

KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/cutouts/western_era5_2019.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '5b811a94-af0f-47c6-8e77-953f4272a76d']

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
Cell In[239], line 2
      1 import xarray as xr 
----> 2 xr.open_dataset("/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/cutouts/western_era5_2019.nc")

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/api.py:525, in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, backend_kwargs, **kwargs)
    513 decoders = _resolve_decoders_kwargs(
    514     decode_cf,
    515     open_backend_dataset_parameters=backend.open_dataset_parameters,
   (...)
    521     decode_coords=decode_coords,
    522 )
    524 overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)
--> 525 backend_ds = backend.open_dataset(
    526     filename_or_obj,
    527     drop_variables=drop_variables,
    528     **decoders,
    529     **kwargs,
    530 )
    531 ds = _dataset_from_backend_dataset(
    532     backend_ds,
    533     filename_or_obj,
   (...)
    541     **kwargs,
    542 )
    543 return ds

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/netCDF4_.py:588, in NetCDF4BackendEntrypoint.open_dataset(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, group, mode, format, clobber, diskless, persist, lock, autoclose)
    567 def open_dataset(  # type: ignore[override]  # allow LSP violation, not supporting **kwargs
    568     self,
    569     filename_or_obj: str | os.PathLike[Any] | BufferedIOBase | AbstractDataStore,
   (...)
    585     autoclose=False,
    586 ) -> Dataset:
    587     filename_or_obj = _normalize_path(filename_or_obj)
--> 588     store = NetCDF4DataStore.open(
    589         filename_or_obj,
    590         mode=mode,
    591         format=format,
    592         group=group,
    593         clobber=clobber,
    594         diskless=diskless,
    595         persist=persist,
    596         lock=lock,
    597         autoclose=autoclose,
    598     )
    600     store_entrypoint = StoreBackendEntrypoint()
    601     with close_on_error(store):

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/netCDF4_.py:389, in NetCDF4DataStore.open(cls, filename, mode, format, group, clobber, diskless, persist, lock, lock_maker, autoclose)
    383 kwargs = dict(
    384     clobber=clobber, diskless=diskless, persist=persist, format=format
    385 )
    386 manager = CachingFileManager(
    387     netCDF4.Dataset, filename, mode=mode, kwargs=kwargs
    388 )
--> 389 return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/netCDF4_.py:336, in NetCDF4DataStore.__init__(self, manager, group, mode, lock, autoclose)
    334 self._group = group
    335 self._mode = mode
--> 336 self.format = self.ds.data_model
    337 self._filename = self.ds.filepath()
    338 self.is_remote = is_remote_uri(self._filename)

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/netCDF4_.py:398, in NetCDF4DataStore.ds(self)
    396 @property
    397 def ds(self):
--> 398     return self._acquire()

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/netCDF4_.py:392, in NetCDF4DataStore._acquire(self, needs_lock)
    391 def _acquire(self, needs_lock=True):
--> 392     with self._manager.acquire_context(needs_lock) as root:
    393         ds = _nc4_require_group(root, self._group, self._mode)
    394     return ds

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/contextlib.py:137, in _GeneratorContextManager.__enter__(self)
    135 del self.args, self.kwds, self.func
    136 try:
--> 137     return next(self.gen)
    138 except StopIteration:
    139     raise RuntimeError("generator didn't yield") from None

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/file_manager.py:198, in CachingFileManager.acquire_context(self, needs_lock)
    195 @contextlib.contextmanager
    196 def acquire_context(self, needs_lock=True):
    197     """Context manager for acquiring a file."""
--> 198     file, cached = self._acquire_with_cache_info(needs_lock)
    199     try:
    200         yield file

File ~/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/xarray/backends/file_manager.py:216, in CachingFileManager._acquire_with_cache_info(self, needs_lock)
    214     kwargs = kwargs.copy()
    215     kwargs["mode"] = self._mode
--> 216 file = self._opener(*self._args, **kwargs)
    217 if self._mode == "w":
    218     # ensure file doesn't get overridden when opened again
    219     self._mode = "a"

File src/netCDF4/_netCDF4.pyx:2449, in netCDF4._netCDF4.Dataset.__init__()

File src/netCDF4/_netCDF4.pyx:2012, in netCDF4._netCDF4._ensure_nc_success()

OSError: [Errno -101] NetCDF: HDF error: '/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/cutouts/western_era5_2019.nc'

```

**Comment by trevorb1** [comment]
okay! Taking a quick look online, seems like other people who get this error flag it as being a corrupt file, or already in use. Can you please: 
- Confirm the `cutouts/western_era5_2019.nc` file on your computer is about `3.4GB` (the same size that should have been downloaded from [Zenodo](https://zenodo.org/records/10067222)). If it isn't the same size, maybe try deleting the file and rerunning the workflow. 
- Confirm that the file is not is use by another program. You can also do a restart of your shell just to make sure the file isn't accidentally open somewhere
- Delete the existing `cutouts/western_era5_2019.nc` and download the file manually from [Zenodo](https://zenodo.org/records/10067222) to see if that works. This one will help us identify if it is a system/dependency issues, as we know the cutout on Zenodo is good. Sorry, I know this one is a bit of a pain, though :(

**Comment by nomineb** [comment]
Hi @trevorb1! I ran the workflow again after cloning the repo, and that seemed to fix the issue. Although I got a solved network, the workflow failed on the last rule, plot_figure. 
`Traceback (most recent call last):
  File "/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/.snakemake/scripts/tmpy75gnkyp.plot_figures.py", line 78, in <module>
    import plotly.express as px
ModuleNotFoundError: No module named 'plotly'
[Tue Dec  5 14:52:28 2023]
Error in rule plot_figures:
    jobid: 1
    input: results/western/networks/elec_s_30_ec_lv1.25_Co2L0.75.nc, resources/western/regions_onshore_s_30.geojson, resources/western/regions_offshore_s_30.geojson
    output: results/western/figures/cluster_30/lv1.25_Co2L0.75_capacity_map_base.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_capacity_map_optimized.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_capacity_map_optimized_brownfield.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_capacity_map_new.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_costs_bar.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_production_bar.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_production_area.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_emissions_area.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_emissions_accumulated.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_emissions_accumulated_tech.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_emissions_map.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_renewable_potential_map.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_capacity_additions_bar.pdf, results/western/figures/cluster_30/lv1.25_Co2L0.75_production_area_html.html, results/western/figures/cluster_30/lv1.25_Co2L0.75_emissions_area_html.html, results/western/figures/cluster_30/lv1.25_Co2L0.75_emissions_region_html.html, results/western/figures/cluster_30/lv1.25_Co2L0.75_emissions_accumulated_tech_html.html

RuleException:
CalledProcessError in file /Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/rules/postprocess.smk, line 22:
Command 'set -euo pipefail;  /Users/nomio/miniforge3/envs/pypsa-usa/bin/python3.11 /Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/.snakemake/scripts/tmpy75gnkyp.plot_figures.py' returned non-zero exit status 1.
  File "/Users/nomio/Documents/REU/Fall_2324/pypsa-usa/workflow/rules/postprocess.smk", line 22, in __rule_plot_figures
  File "/Users/nomio/miniforge3/envs/pypsa-usa/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message`
Is there anything I can do on my end (e.g. import the plotly module)?

**Comment by trevorb1** [comment]
> After I changed the config file, I ran the workflow again but ran into an error in build_renewables_profiles rule again,

Could you please include the the changes you made to the config file here?

**Comment by nomineb** [comment]
Hi @trevorb1 ! I changed operation_only and load_shedding to true, and set co2limit to 1.4728e+1, and cluster to 100. After getting the error, I changed the cluster back to 31, but that didn't not resolve the issue.

**Comment by trevorb1** [comment]
Okay, cool. Thanks! Give me 5min and I will try running both the default and your changes right now to see if I can replicate your error.

**Comment by trevorb1** [comment]
Sorry @nomineb, this is going to have to wait till tomorrow :(

**Comment by ktehranchi** [comment]
@nomineb this is unrelated to the plotting issue but your co2 limit should be 1.4728e+12  (not e+1) if you want to remove the impact of the co2 constraint on the results

**Comment by ktehranchi** [comment]
@nomineb  I tried re-running everything from scratch again and it seems like zenodo is down / the files downloaded form zenodo are corrupt. I was logging download speeds from zenodo in the kb/sec when my internet download was mb/s.

Nomin, did you delete your previously downloaded repository and data? I think in the future when you have issues its a good idea not to delete all the data especially if you have run the workflow successfully before. 

If you would like i can upload the data folder to a google drive for you to download so that you can skip the retrieve data rules.

I'm also confused since you were posting about errors in `plot_results` but then are also having errors in `build_renewable_profiles`??

**Comment by nomineb** [comment]
It would be great to have access to the data folder! 

In the run when the workflow successfully solved the network, it stopped at the ```plot_results``` rule, but when I ran it again after changing the config file, it stopped at the ```build_renewable_profiles``` rule. After that, I deleted the repo and cloned again but ran into the same error in the ```build_renewable_profiles``` rule.

**Comment by ktehranchi** [comment]
I will send you the file via email. but zenodo seems to be back on today so if you ran `snakemake -j1 -F` to rebuild your whole workflow then you should be good.
