### ISSUE TITLE
Integrate Regional Historical Coal Price data

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#151]
### Feature Request

Just like NG prices- we should integrate these coal prices:
https://www.eia.gov/coal/data/browser/#/topic/45?agg=1,0&geo=vvvvvvvvvvvvo&rank=g&freq=Q&start=200801&end=202303&ctype=columnchart&ltype=pin&rtype=s&maptype=0&rse=0&pin=

**Comment by trevorb1** [comment]
Agreed! We are starting to pull in a lot of EIA data, may be worth trying to make our existing getter functions more robust to deal with that as well!

**Comment by ktehranchi** [comment]
Finished with #361
