### ISSUE TITLE
Model Infeasible at Low CO2 Limits

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#157]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

I'm finding that the model does not solve with a CO2L <= ~0.5 and below. 

### Steps To Reproduce

```
scenario:
  interconnect: western #"usa|texas|western|eastern"
  clusters: [30]
  opts:
    [
      Co2L0.05,
      # Co2L1.25-480SEG,
    ]
  ll: [v1.05]
  scope: "total" # "urban", "rural", or "total" 
  sector: "" # G 
```

**Comment by ktehranchi** [comment]
@trevorb1  I think this is connected to the economic retirement setting.

I'm noticing the p_nom_max for extendable non-conventional resources are set to p_nom which is preventing them from being built https://github.com/PyPSA/pypsa-usa/blob/c4972df399a395b78d41544113efc62ac934eb9a/workflow/scripts/add_extra_components.py#L189-L249

shouldn't lines 220 and 226 have the condition of:

``` n.generators["p_nom_max"] = np.where(
        n.generators["p_nom_extendable"] AND if carrier in list gens,
        n.generators["p_nom"],
        n.generators["p_nom_max"]
    )
```

**Comment by trevorb1** [comment]
@ktehranchi I think your right! totally agree that adding in the additional condition of `n.generators["carrier"].isin(gens)` (or similar) will ensure correct retirement
