### ISSUE TITLE
Readthedocs failed 

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#164]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Looks like the readthedocs failed starting from this sector commit: https://github.com/PyPSA/pypsa-usa/commit/c5a2d8c14dac5b900c148ab046e9e050d23f4355

@trevorb1  I think this is from the Sector.csv file but not sure

**Comment by trevorb1** [comment]
Il fix this today
