### ISSUE TITLE
Issues found by Chen

### ISSUE THREAD

**Issue by casinocullen** [PyPSA/pypsa-usa#167]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

- [ ] #170
- [ ] #171
- [ ] #172
- [ ] #173

**Comment by ktehranchi** [comment]
Converted these to individual issues.
