### ISSUE TITLE
Integrate CAISO OASIS Fuel Price Data for the WECC

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#175]
### Feature Request

Higher Quality daily fuel price data for each BA in the WECC lives here: http://oasis.caiso.com/mrioasis/logon.do

### Suggested Solution

- Potential option to write script that calls OASIS API
- Use GridStatus, but this requires API key/account: https://www.gridstatus.io/datasets/caiso_fuel_prices
- Store some historical data in zenodo

**Comment by trevorb1** [comment]
We are starting to pull in costs from all over the place (which I am not against!), but it may be good to break it off into its own module for testing/clarity purposes going forward. Rather than having everything in the `add_electricity` module.

**Comment by ktehranchi** [comment]
Noted- Maybe we can start a build_plant_data module that includes:
- adding temporal fuel costs (EIA / CAISO / other ISOs)
- adding ramp rates / heat rates  EIA

What are your thoughts on the other functions that would be removed from add_electricity?

**Comment by ktehranchi** [comment]
Okay i just saw your other bug for add electricity. ill move this conversation there.
