### ISSUE TITLE
Update logging for ATB data extraction 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#185]
### Feature Request

From a user perspective, it is confusing to see the following logging if you only have (for example) 4hr battery selected as extendable 

```bash
Using OCC for 2hr_battery_storage investment- no ATB CAPEX found.
Missing ATB data for 2hr_battery_storage: ['Variable O&M', 'Heat Rate', 'WACC Real']
Using OCC for 4hr_battery_storage investment- no ATB CAPEX found.
Missing ATB data for 4hr_battery_storage: ['Variable O&M', 'Heat Rate', 'WACC Real']
Using OCC for 6hr_battery_storage investment- no ATB CAPEX found.
Missing ATB data for 6hr_battery_storage: ['Variable O&M', 'Heat Rate', 'WACC Real']
Using OCC for 8hr_battery_storage investment- no ATB CAPEX found.
Missing ATB data for 8hr_battery_storage: ['Variable O&M', 'Heat Rate', 'WACC Real']
Using OCC for 10hr_battery_storage investment- no ATB CAPEX found.
Missing ATB data for 10hr_battery_storage: ['Variable O&M', 'Heat Rate', 'WACC Real
```

**Comment by ktehranchi** [comment]
True... The issue here is that the ATB doesn't have data like heat-rates and VOM for resources where it doesn't make sense for that information to exist- but we are still searching for it regardless if it makes sense. 
Options:
- we just don't print logs for these specific items?
- maybe logger has a method to print to the log file but not show the user in snakemake?

**Comment by trevorb1** [comment]
Totally makes sense for technologies we are implementing! However, it just seems odd we are searching for `10hr_battery_storage` when in the config file I have only specified `4hr_battery_storage` being extendable? So I would expect the logging statement to be: 

```shell 
Using OCC for 4hr_battery_storage investment- no ATB CAPEX found.
Missing ATB data for 4hr_battery_storage: ['Variable O&M', 'Heat Rate', 'WACC Real']
```

Unless we are using the other battery options for something else behind the scenes, then seeing all the logging makes sense!

**Comment by ktehranchi** [comment]
Makes sense... we can hide logs for items not in the config

**Comment by trevorb1** [comment]
I guess my question would be why we are searching though the ATB at all for `10hr_battery_storage` if I didnt specify it in the pypsa config?

**Comment by ktehranchi** [comment]
There are plenty of technologies in build_cost_data that are read from the ATB regardless if they are specified in the config.... I think it's helpful to populate the costs_2030.csv of all the technologies listed in the `constants.py` regardless if they get read into the network. This way build_cost_data doesn't need to be rerun anytime someone changes a carrier in the config file and the user can reference all the technologies available for them to use.

**Comment by trevorb1** [comment]
Fair enough! Thanks for clarifying! :)
