### ISSUE TITLE
Clarify GridEmissions vs. EIA data 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#194]
### Type of documentation issue

Missing Information, Incorect Information

### Issue Description

The current `retrieve_eia_data` rule states the following. But I guess with PR #180 this got switched to directly using GridEmissions data? I know that GridEmissions uses EIA data, but we should probably be giving GridEmissions proper credit as well! :) 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/f4bddf27-7eb4-48c6-bbbf-216ff19f3daf)

### Link to existing documentation

https://pypsa-usa.readthedocs.io/en/latest/rules-retrieving-data.html#rule-retrieve-eia-data

### Suggested Update

I believe [this is the correct repository](https://github.com/jdechalendar/gridemissions?tab=readme-ov-file), however, there are a [couple papers](https://github.com/jdechalendar/gridemissions?tab=readme-ov-file#how-the-datasets-are-created) on the methods there that we may also want to cite.

**Comment by ktehranchi** [comment]
Closed with #209
