### ISSUE TITLE
Update logic for electrical demand in sector studies 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#196]
### Feature Request

More of an issue for the sector coupling studies, but when applying demand it can be hard to determine what is actually included in the electrical demand. For example, when applying the EFS electrical demand, it includes future projections for meeting transport and heating through electrification options. In sector coupling studies, this demand should be treated separately, as the model should be choosing how to meet it. 

### Suggested Solution

May be nice in the demand module to set up a datastructure that can filter by sector and demand type. Then the "business" logic can be how to add these demands together for electrical vs. sector studies. 

This probably deserves a bigger discussion tho! :)

**Comment by ktehranchi** [comment]
Definitely... you'll see a line in my code for EFS demand data where I throw out all the great data on end-uses:
https://github.com/PyPSA/pypsa-usa/blob/1ef05ce3625de68512b2321f187caceec03780ce/workflow/scripts/add_electricity.py#L842C1-L854C1
