### ISSUE TITLE
Production Plots are missformated 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#197]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

When I run a 1-month model, this is the production plot I get. 
- The demand line looks incorrect. This may be due to the `4H` option and the demand not being scaled correctly 
- Batteries are not being grouped correctly 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/47ca1942-3af4-4a5d-8480-f74eead66663)

### Steps To Reproduce

1. clone repo
2. run the workflow

**Comment by ktehranchi** [comment]
The batteries being separated was intentional... 'battery storage' is existing battery storage which I haven't classified into energy capacities. I'll add an issue for that.

And yes- the issue of demand being lower is from the `4H` aggregation.... we need to revisit how we're making these plots.

**Comment by trevorb1** [comment]
Thanks for clarifying!
