### ISSUE TITLE
Can open new zip file under the current naming format in `retrieve_caiso_data`

### ISSUE THREAD

**Issue by casinocullen** [PyPSA/pypsa-usa#215]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

 The issue should come from the colon in the name. After I replaced it with underscore, the error was resolved.
```
  with open(filename, "wb") as file:
         ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'PRC_FUEL_20190101T00:00-0000_20190131T00:00-0000.6.zip'
```

**Comment by ktehranchi** [comment]
Which OS are you running on? This was working for me on Mac.... I'll look into changing this so that it is OS agnostic.

**Comment by ktehranchi** [comment]
Also we should change this so the fuel prices are only downloaded when `interconnect`==`western`

**Comment by casinocullen** [comment]
I am running on Windows. 
Now I added following lines to make it work
```
        startdatetimename = startdatetime.replace(":", "")
        enddatetimename = enddatetime.replace(":", "")
```
