### ISSUE TITLE
EIA API key needed when modeling other than CAISO

### ISSUE THREAD

**Issue by casinocullen** [PyPSA/pypsa-usa#232]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

When building NG prices, now the only options are getting data from EIA or CAISO. If no EIA API key is provided, no data would be prepared and cannot run the rest. 

Recommend to add a third option to provide a default NG price.

Also, seems like that data can't model period >= 2023, so if I am running period in 2023, there comes an error..

**Comment by ktehranchi** [comment]
Do you think we should assert that `dynamic_fuel_price == true` the user must input an EIA API key? 

Or throw a warning and just fall back to the single average fuel cost

@trevorb1  thoughts?

**Comment by casinocullen** [comment]
@ktehranchi That sounds reasonable to me

**Comment by trevorb1** [comment]
@ktehranchi @casinocullen I agree! Asserting that the api key is provided is probably better than a warning, as it can be easy to miss with all the print outs :)

**Comment by trevorb1** [comment]
Also, I add this documentation to the tasks in issue #220
