### ISSUE TITLE
In the function `format_eia_api_data`, many datasets are missing US-level data (e.g. ng_industrial_price) thus will cause an error in the lambda function

### ISSUE THREAD

**Issue by casinocullen** [PyPSA/pypsa-usa#235]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Potential solution is to add  if bool(usa_average) else df["value"] in the end of `apply`
```
    df["value"] = df.apply(
        lambda x: x["value"] if not x["use_average"] else usa_average[x["period"]], 
        axis=1,
    ) if bool(usa_average) else df["value"]
```

**Comment by trevorb1** [comment]
Good call, @casinocullen! This is addressed with the `eia.py` module, and any missing data is replaced with USA average. This function should probably be removed. Relates to Issue #231!
