### ISSUE TITLE
Add Nuclear Fuel Price by State 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#241]
### Feature Request

Right now, uranium fuel costs come in at a national level from the ATB I believe (see issue #63). The [State Energy Data System](https://www.eia.gov/state/seds/seds-data-fuel.php?sid=US) 2022 update has uranium fuel prices at a state level we should look at pulling in.

**Comment by ktehranchi** [comment]
Closing this ticket since we've integrated PuDL fuel prices #361
