### ISSUE TITLE
Ignore git tracking of all config files 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#262]
### Feature Request

More of a question open for discussion, but it would be nice to add all configuration files to the git ignore. That way we have to be quite deliberate about updating them. I think this has three benefits: 
- Any keys will not accidentally be updated (ie. The EIA API key) 
- Simplifies switching between branches if you want to try config options on different features 
- Ensures our default config is tested and we know works 

Just a suggestion! If other people are not into this, thats fine too! :) 

### Suggested Solution

I thought I added the api config to the gitignore in PR #238, but mine is still being tracked. I guess I messed it up haha.

**Comment by ktehranchi** [comment]
Good idea, I support!
