### ISSUE TITLE
If workflow/config doesn't exist init_pypsa_usa.sh error

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#279]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

If the workflow/config folder doesnt already exist, then the init_pypsa_usa.sh script fails with the error message....

### Error Message

```shell
~/Local_Documents/pypsa-usa_mainfork 
 $  bash init_pypsa_usa.sh
ls: workflow/config: No such file or directory
Copying config files from 'workflow/repo_data/config' to 'workflow/config'...
cp: workflow/config is not a directory
```

**Comment by trevorb1** [comment]
@ktehranchi I added a `.gitkeep` to ensure the folder is here upon cloning. But if you think we should modifiy the initialization script instead, please just reopen the issue and I can do that! :)
