### ISSUE TITLE
retrieve_sector_databundle file not downloaded

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#305]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

New error on develop branch:

rule retrieve_sector_databundle:
    output: data/counties/cb_2020_us_county_500k.shp, data/population/DECENNIALDHC2020.P1-Data.csv, data/urbanization/DECENNIALDHC2020.H2-Data.csv, data/natural_gas/EIA-757.csv, data/natural_gas/EIA-StatetoStateCapacity_Jan2023.xlsx, data/natural_gas/pipelines.geojson, data/county_energy/2014_update_20170910-0116.csv
    log: logs/Tutorial/retrieve_sector_databundle.log
    jobid: 11
    reason: Missing output files: data/counties/cb_2020_us_county_500k.shp, data/county_energy/2014_update_20170910-0116.csv
    resources: tmpdir=/var/folders/00/vqry7y9s78q3rvf_m_jmk_bc0000gn/T

INFO:__main__:Downloading pypsa_usa_sec zenodo repository from 'https://zenodo.org/records/10637836/files/pypsa_usa_sector_data.zip?download=1'.
 93% (93 of 100) |###########################################    | Elapsed Time: 0:00:02 ETA:   0:00:00INFO:__main__:Extracting pypsa_usa_sec databundle.
INFO:__main__:pypsa_usa_sec Databundle available in data
Waiting at most 10 seconds for missing files.
MissingOutputException in rule retrieve_sector_databundle in file /Users/kamrantehranchi/Local_Documents/pypsa-usa/workflow/rules/retrieve.smk, line 89:
Job 11  completed successfully, but some output files are missing. Missing files after 10 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
data/county_energy/2014_update_20170910-0116.csv

**Comment by trevorb1** [comment]
Sorry, my bad. Il update this now.

**Comment by trevorb1** [comment]
@ktehranchi you are running `master` branch or `develop` when this error comes up?
