### ISSUE TITLE
Fix pyarrow version for build_cost_data

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#308]
### Checklist

- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### Issue exisits on what branch

Master

### The Issue

A new user who just downloaded the repo had pyarrow version 14.0.0, and he got an error on build_cost_data

Solution: pip installed back to `pyarrow==13.0.0`

**Comment by trevorb1** [comment]
@ktehranchi; I am having trouble recreating this issue! :( 

I did a clean install of the `pypsa-usa` environment and everything worked fine. I am running pandas `2.2.2` and pyarrow `15.0.2` (the default install versions) and successfully ran `build_demand` on the `master` branch. Additionally, I tried with pyarrow versions `13.0.0`, `14.0.0`, and `14.0.2` and did not run into an issue. I ensured I was running `EFS` data, as this uses the pyarrow engine. Perhaps it is an issue with the pandas/pyarrow versions. Do you know the version of pandas the user was running?

**Comment by ktehranchi** [comment]
Okay weird.... I guess this was a different issue with the users conda environment then. Ill close. Thanks for checking!
