### ISSUE TITLE
`p_nom_min` is negative for some renewables

### ISSUE THREAD

**Issue by casinocullen** [PyPSA/pypsa-usa#309]
### Checklist

- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### Issue exisits on what branch

Master

### The Issue

I don't understand why some generator has negative `p_nom_min`, like in the screenshot below 
![Screenshot 2024-05-02 at 11 42 42 AM](https://github.com/PyPSA/pypsa-usa/assets/35535471/c797005f-9408-478d-9f55-0bc059543fdd)

**Comment by ktehranchi** [comment]
Which network are you referring to? ie is this the output of solve_network? 

I am pretty this is done intentionally for numerical reasons at some point (maybe during solving) from the pypsa or pypsa-eur implementation but need to confirm.
