### ISSUE TITLE
GenX link is not working

### ISSUE THREAD

**Issue by aljubrmj** [PyPSA/pypsa-usa#315]
### Type of documentation issue

Incorect Information

### Issue Description

The GenX link associated with the description of the `operational_reserve` variable is not working. Please update. Thanks! 

### Link to existing documentation

https://pypsa-usa.readthedocs.io/en/latest/config-configuration.html

**Comment by trevorb1** [comment]
Thanks for reporting, @aljubrmj! Just to confirm, you are running linopy `0.3.8` as per issue #163?

**Comment by ktehranchi** [comment]
@trevorb1 He just means the link to the genX website on our docs is broken.

**Comment by trevorb1** [comment]
ohhh sorry. My bad!
