### ISSUE TITLE
Inconsistency in Production Plots

### ISSUE THREAD

**Issue by aljubrmj** [PyPSA/pypsa-usa#317]
### Checklist

- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### Issue exisits on what branch

Master

### The Issue

When running `config.tutorial.yaml`, the resultant total generation does not match demand throughout. It _may_ be related to how battery dis/charge is plotted here.

[production_area.pdf](https://github.com/PyPSA/pypsa-usa/files/15227637/production_area.pdf)

### Steps To Reproduce

`snakemake -j6 --configfile config/config.tutorial.yaml`

### Expected Behavior

Supply = Demand

**Comment by trevorb1** [comment]
I agree, probably a battery plotting issue! Also relates to issue #197
