### ISSUE TITLE
Source EIA AEO from PUDL

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#339]
### Feature Request

For future work that utilizes the AEO- we should go to the PUDL table that contains this data.

Data:
https://catalystcoop-pudl.readthedocs.io/en/nightly/data_dictionaries/pudl_db.html#core-eiaaeo-yearly-projected-generation-in-electric-sector-by-technology

Relevant modules:

- We'll need to access to this data in `build_demand` that's likely the place where accessing the sqlite db makes the most sense.

**Comment by trevorb1** [comment]
@ktehranchi Exploring the PUDL data from the AEO, I think maybe discussing this first would be good. 

Right now I am planning to scale electricity only demand by total electricity projections, or end use energy demand for sector studies. PUDL is giving us [electricity generation](https://data.catalyst.coop/pudl/core_eiaaeo__yearly_projected_generation_in_electric_sector_by_technology), and [end use fuel](https://data.catalyst.coop/pudl/core_eiaaeo__yearly_projected_generation_in_end_use_sectors_by_fuel_type) (natural gas, coal, ect...), which are not sector specific, or only [electricity sales](https://data.catalyst.coop/pudl/core_eiaaeo__yearly_projected_electric_sales) for sector specific. This makes it difficult to coordinate a single dataset for both electricity/sector studies as PUDL does not give energy consumption by sector (which AEO does have). 

Alternatively, I could use AEO heating/cooling degree day projections as a proxy for cooling and heating demand growth in the residential/commercial sector, but that will make breaking out electricity specific from heating/cooling difficult, and isnt really a great solution for the industrial sector. 

Do you have any thoughts on this? Right now I would propose to just use the current AEO demand we pull to scale demand, as that way everything comes from a single source and we minimize conditional logic.

**Comment by ktehranchi** [comment]
Yep- I agree it's definitely a good idea to source the AEO projects from one single point since PUDL doesn't have sector-level projects from AEO. Good point!

**Comment by trevorb1** [comment]
Scaling electricity growth now comes from PUDL. Sector studies still pull from EIA API directly.
