### ISSUE TITLE
Must run capacity ratings not being applied 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#344]
### Checklist

- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### Issue exisits on what branch

Develop

### The Issue

Must run capacity ratings executes in `add_electricity`, but the result dataframe is empty. This example below is just for texas. 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/bf627cc7-f2e9-4ad5-8f74-0b09c866d34f)

### Steps To Reproduce

Run the workflow for just texas

**Comment by ktehranchi** [comment]
This isn't a bug, we don't have must-run status designation data for non-wecc resources. I will close this with d350dc9 which also adds minimum loading for the entire US when unit commitment is enabled. Data for Minimum loading comes from pudl/eia860

**Comment by trevorb1** [comment]
Thanks for clarifying, @ktehranchi!
