### ISSUE TITLE
workflow testing

### ISSUE THREAD

**Issue by martacki** [PyPSA/pypsa-usa#387]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Hi, I'm just running the workflow again after a while, and am impressed how much it has changed! Great to see evolution here

Just a few things, but I didn't have the time to check if this is intended or maybe I am using the modified workflow incorrectly:

First of all, I had to delete the whole validation rules, because the corresponding config files seem to be missing, which seems to create issues (at least for me).

After that, for the Snakefile to find the config files, I needed to change their paths:
```
configfile: "repo_data/config/config.validation.yaml"
configfile: "repo_data/config/config.cluster.yaml"
configfile: "repo_data/config/config.common.yaml"
configfile: "repo_data/config/config.plotting.yaml"
configfile: "repo_data/config/config.api.yaml"
```

originally, `repo_data` was not present in the path. With this I am able to at least create the base network.

After that, proceeding to adding ppls etc., retrieving the pudl data seems not to work. According to the terminal, the pudl link does not exist. If I copy it to my browser, it also seems not to be there. Maybe a typo?

Thanks to the help!

**Comment by ktehranchi** [comment]
Hi Marta! 
To move the configs to the right directory you need to run `bash init_pypsa_usa.sh` per install instructions: https://pypsa-usa.readthedocs.io/en/latest/about-install.html

Regarding PUDL- Maybe their link just changed recently since they had some releases- I'll double check that, thanks!

**Comment by ktehranchi** [comment]
@martacki Fixed the PUDL link!

**Comment by martacki** [comment]
Thanks @ktehranchi ! It runs now at master after copying all `config.x.yaml` files and `policy_constraints/` from `repo_data/` into `configs/`. The updated PUDL link also works. 

I just wonder if all `config.x.yaml` files and `policy_constraints/` _have to_ be copied from `repo_data/` into `configs/`, why they aren't initially already in the `configs/` folder ? Might be a barrier for other users if not familiar with Snakemake, and the error reads as if those files don't exist. Is there a specific reason for it?
