### ISSUE TITLE
Documentation: Set ReEDS network for transmission data

### ISSUE THREAD

**Issue by JPMartinezClaeys** [PyPSA/pypsa-usa#441]
### Type of documentation issue

Incorect Information, Typo

### Issue Description

In Model Data, in [Transmission](https://pypsa-usa.readthedocs.io/en/latest/data-transmission.html) there are some instruction on how to run the model using the ReEDS network. 
The documentation indicates to use the ReEDS network in PyPSA-USA to enable the `links: transport_model` setting. In the file `workflow/config/config_default.yaml`, `links` does not have a `transport_model` wildcard but `lines` does which might be a typo in the documentation.

### Link to existing documentation

https://pypsa-usa.readthedocs.io/en/latest/data-transmission.html

### Suggested Update

Modify in the documentation enable the `links: transport_model` to enable the `lines: transport_model`

**Comment by ktehranchi** [comment]
Thanks for noting this typo! 

We are planning a release this week that restructures how you select transmission networks- so keep an eye out!
