### ISSUE TITLE
The number of clusters could not be customized

### ISSUE THREAD

**Issue by huainie** [PyPSA/pypsa-usa#467]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

I changed the default configuration file area to California and only the renewable energy. I set the number of clusters to 10 and the error message to 4.0. In addition, the clustering algorithm can only use KMEANS, not HAC.
os：win10 

### Expected Behavior

scenario:
  interconnect: [western] # "usa|texas|western|eastern"
  clusters: [10]
  simpl: [50]
  opts: [REM-3h]
  ll: [v1.0]
  sector: "" # G
  planning_horizons: [2030, 2040, 2050]    #(2018-2023, 2030, 2040, 2050)

model_topology:
  transmission_network: 'reeds' # [reeds, tamu]
  topological_boundaries: 'reeds_zone' # [county, reeds_zone]
  interface_transmission_limits: false
  include: # mixed zone types not supported
    reeds_state: ['CA'] 

### Error Message

```shell
INFO:pypsa. io: Imported network elec_s50.nc has buses, carriers, generators, lines, links, loads, storage unitsINFO:ma1n:Aggregating to transport model with reeds zone zones.INFO :main :Using Transport Mode1.Traceback(most recent call last):File "D: \pypsa-usa workflow. snakemake\scripts(tmpfsga3tyf.cluster network.py", line 672, in <module》assert n clusters = len
ssertionErrdNumber of clusters must be 4 for current configuration..23:43 2024Mon Nov 4 08.Error in rule cluster network:
```

### Anything else?

I'd like to see more clusters of renewable energy in California

**Comment by ktehranchi** [comment]
The error message is telling you that you need to change the number of clusters to 4. This is because you are using the reeds transmission network which has a pre-fixed number of nodes per state.

see instructions here: https://pypsa-usa.readthedocs.io/en/latest/config-spatial.html
