### ISSUE TITLE
Update Storage Costs to be USA data

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#58]
### Feature Request

To apply costs, `TechnologyData` (ie. the PyPSA-Eur data) is used a as a backbone. Then USA data (ie. ATB, EIA, ect...) replace the European data where ever possible. [This comment](https://github.com/PyPSA/pypsa-usa/pull/44#issuecomment-1731732162) has a list of major differences between the datasets. 

One exception is the cost data for electrical batteries, which was very different between PyPSA-Eur and PyPSA-USA. Right now, PyPSA-Eur data has been applied for this; this needs to be updated and an explanation of the cost difference should be found. 

### Suggested Solution

It may be a simple incorrect mapping of technologies, otherwise, looking at the assumptions for each technology is probably needed 

### Additional Info

Here is where the code skips applying the USA data 

https://github.com/PyPSA/pypsa-usa/blob/6f37e32de0b19b349e6ba134e1bcfa0f48e5b93a/workflow/scripts/build_cost_data.py#L264-L291

**Comment by ktehranchi** [comment]
#148 Changed the way build_cost_data integrated the NREL ATB:
> Updates build_cost_data: a) The "default" technology class from the NREL ATB is selected before any user-set parameters b) The user can now add any technology from the ATB by adding their choice of technology in the constants file.
