### ISSUE TITLE
Incorrect Ramping Limits 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#60]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Ramping limits for generators are being incorrectly applied. As per the[ PyPSA documentation](https://pypsa.readthedocs.io/en/latest/components.html#generator), they should be applied at a per unit level; instead they seem to be applied at an absolute value. 

### Steps To Reproduce

1. Run the default workflow `snakemake -j6`
2. Read in the network
```python 
 n = pypsa.Network()
n.import_from_netcdf("../workflow/results/western/networks/elec_s_60_ec_lvopt_Co2L1.0.nc")
```
4. Check ramp rate on generators 
```python 
n.generators[~(n.generators.ramp_limit_up.isna())]
```
![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/bcde8c63-36a2-4eb5-98ca-539732441021)

### Expected Behavior

`ramp_limit_up` and `ramp_limit_down` should be applied at a per unit of nominal power level (ie. a value between 0 and 1)

**Comment by ktehranchi** [comment]
Will address this in #56 !

**Comment by ktehranchi** [comment]
Ramping rates are actually not an issue here, NG plants can ramp faster than 1 pu per hour, and that's why the ramp rates are high!

**Comment by trevorb1** [comment]
Totally fair! Especially from an aggregated point of view, I think that makes sense. Just to note, I think 860 still classifies a lot of CCGT into the 1-12hr ramp time (albiet from cold start). Moreover, its probably closer to 1hr than 12hr in most cases; so again, I agree with your assumption! OCGT are basically all classified as 10min. 
- [About 25% of U.S. power plants can start up within an hour](https://www.eia.gov/todayinenergy/detail.php?id=45956#)
- Form 3.1 [here](https://www.eia.gov/electricity/data/eia860/)

From a clarity perspective, do you think we should change the ramp limits to be `1.0`?

**Comment by ktehranchi** [comment]
Interesting- I didn't see that field from the 860..... one thing to note right now is we only have ramp rates for plants in the WECC from the ads... need to add plants for the rest of the US, and could probably use that field as an approximate. Problem is that Time from cold-start to full load != ramp rate... because start-up time shouldn't be included in ramp rate.

Could you explain what you mean by "From a clarity perspective, do you think we should change the ramp limits to be 1.0?"

**Comment by trevorb1** [comment]
>Problem is that Time from cold-start to full load != ramp rate... because start-up time shouldn't be included in ramp rate.

I agree! 

> Could you explain what you mean by "From a clarity perspective, do you think we should change the ramp limits to be 1.0?"

Ramp limits are defined on a per unit basis, so setting the ramp limit to `1.0` will accomplish the same thing and aligns with pypsa component definition. Functionally it should be the same (I believe), just clearer imo for new users. 

> Ramping rates are actually not an issue here

Also, I havent checked if coal plants have been corrected from when this screenshot was taken, but coal plant ramping limits probably shouldnt be `1.0`?

**Comment by ktehranchi** [comment]
> Ramp limits are defined on a per unit basis, so setting the ramp limit to 1.0 will accomplish the same thing and aligns with pypsa component definition. Functionally it should be the same (I believe), just clearer for new users?

True

> Also, I havent checked if coal plants have been corrected from when this screenshot was taken, but coal plant ramping limits probably shouldnt be 1.0?

I'll revisit this.

**Comment by ktehranchi** [comment]
@trevorb1  I reviewed this and I think the coal ramping rates are correct. You can see below that in [PyPSA-Eur they use 1.0](https://github.com/PyPSA/pypsa-eur/blob/180d93951dc8c8b1cca35568f8ed4ca74f5abe42/data/unit_commitment.csv#L4) for coal ramping. 

From[ this report](https://www.nrel.gov/docs/fy20osti/77639.pdf) also:

> On average, the coal-based power plants around the world have ramp rates within the range of 1%–4% per
> minute, combined cycle gas turbines are between 2%–4%, and open cycle gas turbines are within the range of
> 8%–12%. State-of-the-art coal-based plants can even achieve ramp rates of up to 6% per minute, whereas state-of-
> the-art combined cycle gas turbines can achieve 8%–10%, and open cycle gas turbines up to 15% (Agora 2017;
> EPPSA 2015). In Denmark, thermal power plants are either built or retrofit to provide 4% ramp rate. Retrofit
> measures in Germany (Boxberg and Walsum Power Plant) allowed power plants to achieve ramp rates up to 6%.
> The new Belchatow II Unit1 in Poland can provide a ramp rate of 2%–6%. Nuclear plants are generally
> considered inflexible, but they also offer some flexibility in countries like Germany and France (Agora 2015).
> Internal combustion engines can provide fast ramping of around 100% (IRENA 2019). Hydro generators can
> provide ramp rates of the order of 10%–30% per minute; however, this flexibility may be restricted at times due
> to various environmental constraints.

**Comment by trevorb1** [comment]
Totally fair, thanks for clarifying @ktehranchi! :)
