### ISSUE TITLE
EIA Historical Fuel Data not aligned with Fuel_Year Configuration

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#62]
### Feature Request

The `retrieve_cost_data_usa` rule will grab historical natural gas prices for 2022, and apply these as the natural gas fuel costs at a state level. It would be nice to add in a configuration option to allow a user to select whatever historical year they want. 

### Suggested Solution

Add a configuration option like. 

```yaml 
costs:
  fuel:
    eia_year: 2022
```

### Additional Info

May also be related to issue #59

**Comment by ktehranchi** [comment]
Could we take the snapshot year config for this? instead of adding a new config?

https://github.com/PyPSA/pypsa-usa/blob/6f37e32de0b19b349e6ba134e1bcfa0f48e5b93a/workflow/config/config.yaml#L44

**Comment by trevorb1** [comment]
Oh! Yeah, great idea! That will work out perfectly!

**Comment by ktehranchi** [comment]
#209 Added option to pull historical fuel costs from CAISO. 

@trevorb1 When we pull historical EIA data we can use this same field. Changing name to identify issue is with EIA data retrieval.

**Comment by trevorb1** [comment]
Adding in the issue of filling in missing values with `2022` data. Functionality is there with the `eia.py` module to address both of these issues. Moreover, this is tied to issue #151. 

Addressing issue #206 should be done with these other issue tickets.

**Comment by trevorb1** [comment]
Closed with PR #226
