### ISSUE TITLE
Integrate Texas and Eastern Interconnects

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#70]
### Feature Request

This is a long-time standing back-burner task to integrate Texas and Eastern interconnections. Currently, only WECC runs in pypsa-usa configuration.

### Suggested Solution

- Map load data balancing authorities to the BA names in the network. This could mean aggregating some of the given BA's in the south. 
- Fixing BA shape files to fill gaps between BAs where nodes may lay
- Build a new cutout for the entire US or multiple cutouts for each interconnection

**Comment by trevorb1** [comment]
@ktehranchi, how far into this issue are you? No rush, but just note in my fix for issue #76 (see PR #84) I have created new cutouts for each interconnection. I can pass those along if needed. Moreover, I am happy to help with the other items on this list as well if needed :)

**Comment by ktehranchi** [comment]
I haven't started on this, but this is in my docket for this week. Thanks for making these build cutout changes... Did you build the cutouts locally already? Whats your thoughts on have the cutouts pre-built and loaded on zenodo versus using the build_cutouts?

If we were to go the zenodo route, it would make sense to just have one cutout for the entire US for each year 2017-23, then filtering the cutout spatially for each interconnect... otherwise we would have 4 cutouts X 6 years.

I can complete the tasks for the load and plant data + GIS work on this issue.

**Comment by trevorb1** [comment]
I created the cutouts for `Western`, `Eastern`, and `Texas` locally (for 2019), and the one for `usa` is currently running. 

I totally agree with your point on keeping them on Zenodo, and the `build_cutout` rule only being triggered if the user specifies it in the config file. Moreover, I like your point of to"just have one cutout for the entire US for each year 2017-23". Probably easier than having different interconnect cutouts!

If we are wanting to give users the option to create a cutout for their interconnection though (through `build_cutout`), we will probably need to change the `cutout` argument to be an input function for any rule that uses it, I think. Something like (untested) 

```python 
def cutout_file(wildcards):
    if config["enable"].get("build_cutout", False):
        return "cutouts/" + CDIR + "wildcards.cutout.nc"
    else:
        return "cutouts/" + CDIR + "wildcards.interconnect_wildcards.cutout.nc"
```

**Comment by ktehranchi** [comment]
Cutouts now uploaded to sandbox [zenodo](https://sandbox.zenodo.org/record/1245562) with texas and eastern interconnect for 2019

**Comment by trevorb1** [comment]
I have tried making a cutout for the `usa` a couple times, but it seems to get stuck. It runs for multiple days and just stays at 2% complete. @ktehranchi, have you tried the full `usa` cutout?

**Comment by ktehranchi** [comment]
that happened with my texas run. I just had to rerun it once or twice and it was completed.... I'll give USA a run tonight and let you know.

**Comment by trevorb1** [comment]
I tried rerunning `usa` cutout as well and it worked on my side! If you need me to share it with you for upload to Zenodo, just let me know! 

Another note, I think the current cutouts uploaded to Zenodo are different resolutions. For example, see `western` and `texas` shown below, which I just re-downloaded from Zenodo. It may be good to sync these to the config file avoid confusion? Currently, the defaults are `0.3` degrees for both `x` and `y`, but can be updated to `0.25`! 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/ea34e598-7f2a-463a-a361-c1ecc19926ea)

https://github.com/PyPSA/pypsa-usa/blob/2707c3c079fe59ed6b512356e84dbdd058caf14d/workflow/config/config.default.yaml#L61-L81

**Comment by ktehranchi** [comment]
sweet! Yeah if you send it somehow, I can upload it on my end. I cant find a way on zenodo to give you permission to upload more.... I will recreate the Western too so it has the same resolution.
