### ISSUE TITLE
Move Zenodo links out of the `config.yaml`

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#79]
### Feature Request

More of a question, but having the Zenodo links in the config file seems odd. Since the downstream logic is set up to only work with the data structures returned from these specific Zenodo deposits, it seems like these should not be configuration options. Rather, they should be hard coded into the `Snakefile`? 

https://github.com/PyPSA/pypsa-usa/blob/bb9e5129e03e952cadc9a9f6e3d7cdb5914ebb88/workflow/config/config.yaml#L20-L26

@ktehranchi, what are your thoughts on this?

**Comment by ktehranchi** [comment]
Yep- we should do this! I can get this done

**Comment by ktehranchi** [comment]
Solved with https://github.com/PyPSA/pypsa-usa/commit/9a75ef918eebd2c791b532f0f03ea18696db8ee6

**Comment by ktehranchi** [comment]
closed by #109
