### ISSUE TITLE
Transmission Line Voltages 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#90]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

There seems to be an inconsistency of the Breakthrough Energy's transmission line voltages. Specifically, I think the data processing of BE into PyPSA is correct, but the interpretation of the data may be off. 

I have [included a notebook of this issue](https://github.com/trevorb1/pypsa-usa/blob/tranmission-voltage/workflow/notebooks/transmission_lines.ipynb), and will describe the issue using `765kV` lines as an example. 

**PyPSA-USA network**
If I run the workflow, and import the network before any simplification/clustering, this is the result. The bold red lines are `765kV`. 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/3526003c-a3d0-470b-a453-77ef33f95681)

**Breakthrough Energy**
If I do the mapping of buses/subs to highlight the `765kV` buses, these are the locations. This match up with the PyPSA-USA representation -- this is why I think the data processing is correct 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/73948a57-740a-4c19-8dac-a6aaeb0a8ded)

**Geospatial Management Office**
If I take the [geospatial management offices](https://hifld-geoplatform.opendata.arcgis.com/datasets/geoplatform::transmission-lines/about) gis data on USA transmission lines and plot it, this is the result for `765kV` lines. Notably, there are none in the western interconnect. Moreover, the existing `765kV` lines in the north east do not appear on the breakthrough energy dataset. I have confirmed that the `765kV` lines in this dataset are correct. 

![image](https://github.com/PyPSA/pypsa-usa/assets/67297083/4240161e-f4a6-4806-9612-987cc30b8514)

### Steps To Reproduce

1. Run workflow 
2. Run the [notebook](https://github.com/trevorb1/pypsa-usa/blob/tranmission-voltage/workflow/notebooks/transmission_lines.ipynb)

### Expected Behavior

I would expect the two separate datasets to at least be similar. The [geospatial management offices](https://hifld-geoplatform.opendata.arcgis.com/datasets/geoplatform::transmission-lines/about) `765kV` lines should be present in the BE dataset? 

### Anything else?

@ktehranchi do you have any immediate thoughts on this issue? If not, maybe we can meet up to discuss the differences between the datasets to try and figure out where the differences are coming from?

**Comment by ktehranchi** [comment]
This is just an issue with how the Breakthrough/TAMU Transmission network is created. It's a synthetic network and they created it so that the capacities and dispatch loosely matches historical data. There was a project at BE to load the HIFLD dataset you posted into the model, but they didn't get that far since there are issues with ensuring network connectivity with that dataset. 

this is a project I might be taking on in the next year... can share more when we chat.

**Comment by ktehranchi** [comment]
Closing- as discussed this is part of the issue with synthetic networks.
