### ISSUE TITLE
New Results Plots

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#93]
### Feature Request

- [x] New capacity versus total installed capacity
- [x] All plot with labels and titles
- [x] Emissions by node
- [x] Wildcards displayed on the titles
- [ ] Output tables and charts of all capex, marginal cost, opex for each plant , plant type
- [x] map of renewable capacity potential at each node

**Comment by trevorb1** [comment]
@ktehranchi Does the branch `93-new-results-plots` have your most up to date changes for this issue? I was going to hop on this one as well to help out as well! :) 

If `93-new-results-plots` does have your most up to date changes, did you want to draft a PR and then I will start adding to that branch? Just want to make sure you don't have commits that havent been pushed yet before I start pushing changes.
